### ISSUE TITLE
 SoGui.init(sys.argv[0]) run error

### ISSUE THREAD

**Issue by CaeCoder** [coin3d/pivy#100]
call code：myWindow = SoGui.init(sys.argv[0])，there throw error

Traceback (most recent call last):
  File "D:\Temp\pivy\pivy-master\examples\Mentor\02.1.HelloCone.py", line 63, in <module>
    main()
  File "D:\Temp\pivy\pivy-master\examples\Mentor\02.1.HelloCone.py", line 34, in main
    myWindow = SoGui.init(sys.argv[0])
  File "D:\Software\Software_Install\Anaconda3\lib\site-packages\pivy\sogui.py", line 123, in init
    return pivy.quarter.QuarterWidget()
  File "D:\Software\Software_Install\Anaconda3\lib\site-packages\pivy\quarter\QuarterWidget.py", line 204, in __init__
    QuarterWidget._sensormanager = SensorManager()
  File "D:\Software\Software_Install\Anaconda3\lib\site-packages\pivy\quarter\SensorManager.py", line 51, in __init__
    SoDB.getSensorManager().setChangedCallback(self.sensorQueueChangedCB, self)
  File "D:\Software\Software_Install\Anaconda3\lib\site-packages\pivy\coin.py", line 4068, in setChangedCallback
    return _coin.SoSensorManager_setChangedCallback(self, sensorQueueChangedCB, data)
TypeError: in method 'SoSensorManager_setChangedCallback', argument 2 of type 'void (*)(void *)'
Exception ignored in: <function SensorManager.__del__ at 0x000001D914F48280>
Traceback (most recent call last):
  File "D:\Software\Software_Install\Anaconda3\lib\site-packages\pivy\quarter\SensorManager.py", line 58, in __del__
    if self._signalthread.isRunning():
RuntimeError: Internal C++ object (SignalThread) already deleted.

**Comment by marioalexis84** [comment]
https://github.com/coin3d/pivy/pull/99 solve this.

**Comment by CaeCoder** [comment]
I update to the latest pivy (2022-08-25), recompile, and this error still exist.

**Comment by CaeCoder** [comment]
run #99，run below code，there is error _TypeError: in method 'SoSensorManager_setChangedCallback', argument 2 of type 'void (*)(void *)'_
from PySide2.QtWidgets import QApplication
from pivy import quarter
app = QApplication()
q = quarter.QuarterWidget()

**Comment by CaeCoder** [comment]
my python environment is  "Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32"

**Comment by marioalexis84** [comment]
How are you recompiling?
Can you try a full rebuild? Currently, changes  to the SWIG interface file `pivy_common_typemaps.i` don't trigger a rebuild.

**Comment by CaeCoder** [comment]
I recoimpile with cmake-gui configure setting Visual Studio 2017 X64，swig4.0.0，Qt5 items selected Anaconda install directory。I deleted all build files and folder before compile。recompiled，run Install project to make pivy package in Anaconda Lib/Site-package/pivy
