### ISSUE TITLE
'pivy._coin' has no attribute 'delete_SoGeo'

### ISSUE THREAD

**Issue by DaveCoventry** [coin3d/pivy#102]
Hi, I am getting the following error:

`dave@Tuffy:~$ python3
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pivy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pivy/__init__.py", line 30, in <module>
    from .coin import SoDB, SoNodeKit, SoInteraction
  File "/usr/lib/python3/dist-packages/pivy/coin.py", line 40397, in <module>
    class SoGeo(object):
  File "/usr/lib/python3/dist-packages/pivy/coin.py", line 40431, in SoGeo
    __swig_destroy__ = _coin.delete_SoGeo
AttributeError: module 'pivy._coin' has no attribute 'delete_SoGeo'
>>> 
`

OS: KDE neon 5.26 (KDE/plasma)
Python 3.10.6, Qt 5.15.7, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.1

**Comment by looooo** [comment]
I guess this is an packaging issue.

**Comment by DaveCoventry** [comment]
I cloned pivy and installed with cmake and make.

**Comment by looooo** [comment]
ok, strange. which swig version are you using? I saw recently some issues with swig 4.1.0 and pythonocc-core. Maybe this can be related.

**Comment by DaveCoventry** [comment]
`dave@Tuffy:~$ swig -version

SWIG Version 4.0.2

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre
`

**Comment by iplayfast** [comment]
I just came across this as well, many of my addon modules give this error.
Exact same swig version.

Another clue perhaps is 
python
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pivy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/github/pivy/build/pivy/__init__.py", line 30, in <module>
    from .coin import SoDB, SoNodeKit, SoInteraction
  File "/home/chris/github/pivy/build/pivy/coin.py", line 21, in <module>
    from . import _coin
ImportError: cannot import name '_coin' from partially initialized module 'pivy' (most likely due to a circular import) (/home/chris/github/pivy/build/pivy/__init__.py)

I think it has something to do with https://github.com/coin3d/pivy/issues/103

**Comment by DaveCoventry** [comment]
Hi Chris,

Did you find a workaround for this issue?

**Comment by looooo** [comment]
It's possible that different versions of pivy causing this problem. Please check which _coin.so is used. If I can remember correctly SoGeo was added recently.
