### ISSUE TITLE
 Cannot import quarter with pyside6 (cannot find QOpenGLWidget)

### ISSUE THREAD

**Issue by je-cook** [coin3d/pivy#129]
Hi, on testing out the freecad v1 build on conda-forge I ran across a failure to import quarter from pivy. I made a fresh conda env just with `PySide6` and `pivy` to isolate it. I get the same error across python 3.10, 3.11 and 3.13

The import that is failing is seemingly here where the pyside6 import fails and it falls back to the pyside2 import:
https://github.com/coin3d/pivy/blob/85dffc6a735c73159af3fc490ee74836f023e1b4/pivy/quarter/QuarterWidget.py#L116

```python
Python 3.13.0 | packaged by conda-forge | (main, Oct  8 2024, 20:04:32) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pivy
>>> from pivy import quarter
Traceback (most recent call last):
  File ".../miniforge3-latest/envs/pivy/lib/python3.13/site-packages/pivy/quarter/QuarterWidget.py", line 116, in <module>
    from pivy.qt.QtOpenGLWidgets import QOpenGLWidget
ModuleNotFoundError: No module named 'pivy.qt.QtOpenGLWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    from pivy import quarter
  File ".../miniforge3-latest/envs/pivy/lib/python3.13/site-packages/pivy/quarter/__init__.py", line 17, in <module>
    from . import QuarterWidget
  File "/.../miniforge3-latest/envs/pivy/lib/python3.13/site-packages/pivy/quarter/QuarterWidget.py", line 118, in <module>
    from pivy.qt.QtWidgets import QOpenGLWidget
ImportError: cannot import name 'QOpenGLWidget' from 'pivy.qt.QtWidgets' (.../miniforge3-latest/envs/pivy/lib/python3.13/site-packages/pivy/qt/QtWidgets/__init__.py)
>>>

**Comment by looooo** [comment]
can you check if https://github.com/coin3d/pivy/pull/130/commits/3bc3cd5eb33ab0d5286ccf2e231529fbc95590f2 fixes this issue?

**Comment by je-cook** [comment]
Yes that fixes it, thankyou and thanks for the quick response!
